---
name: WWW-Live365
version: 0.12
author:
  - 'Earle Martin <hex@cpan.org>'
abstract: get Live365.com audio stream URLs
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  WWW::Mechanize: 0
build_requires:
  Net::Ping::External: 0
  Test::More: 0
  Test::Pod: 1
  Test::Pod::Coverage: 0
  Test::Without::Module: 0
provides:
  WWW::Live365:
    file: lib/WWW/Live365.pm
    version: 0.12
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
